pub const CITIES: &[&'static str] = &[
    "Campo Grande",
    "Juazeiro",
    "Goiânia",
    "Maceió",
    "Belém",
    "Belo Horizonte",
    "Porto Alegre",
    "Salvador",
    "Vila Velha",
    "Yarrawonga",
    "Crosa",
    "Wirie",
    "Sonoma",
    "Scicli",
    "Griaphia",
    "Pupus",
    "Fayetteville",
    "Gundagai",
    "Luehlas",
    "State College",
    "Zriledo",
    "Gaburg",
    "Srumgate",
    "Blibridge",
    "Encebridge",
    "Dradence",
    "Ensmore",
    "Tamaqua"
];