pub const CLIENTS: &[&'static str] = &[
    "Limner Studio",
    "Life Paths",
    "PrimeHouse",
    "Find Agenda",
    "Et Cetera Systems",
    "Handy Help",
    "Puzzles",
    "DualLight",
    "Radiate Random",
    "Resource Refresh",
    "XyloFurniture",
    "TRUE Random",
    "Light Random",
    "FirstVictory",
    "Node Tech",
    "Odds And Ends",
    "Odd And Ends",
    "Adventures",
    "Forel Library",
    "Silence Center",
    "Authority Random",
    "Spiritual Beings",
    "Random Row",
    "X Marks The Spot",
    "Spray Shop",
    "Cellar Random",
    "Pop-Culture",
    "In A Pinch",
    "Et Cetera",
    "Missed Opps",
    "CraftCreate",
    "Empty Particles",
    "Though Random",
    "Essentials",
    "Airhead",
    "Motion Random",
    "Sporadic Systems",
    "FursKips",
    "Resource Random",
    "Muno Random",
    "Random Riders",
    "23Rd Century",
    "Destroy Random",
    "Vappa Shop",
    "Random Repair",
    "Fleet Random",
    "Knick Knacks",
    "Absent-Minded",
    "Random Reason",
    "Eclipse Random",
    "The Source",
    "Cowboy Random",
    "Million Random",
    "Herb Random",
    "Nick Knacks",
    "Sense Random",
    "Random Refresh",
    "Lifestyle Random",
    "Shady Bootz",
];