pub const PRODUCTS: &[&'static str] = &[
    "Picanha",
    "Alcatra",
    "Contra filé",
    "Filé mingnon",
    "Chandanga",
    "Maminha",
    "Lagarto",
    "Cupim maturado",
    "Peito bovino",
    "Acém bovino",
    "Paleta bovino",
    "Pexinho bovino",
    "Capa do coxão mole",
    "Capa do contra filé",
    "Costela Bovina",
    "Lombo",
    "Costelinha",
    "Pernil com osso",
    "Toucinho",
];