pub const STATES: &[&'static str] = &[
    "Distrito Federal",
    "Goias",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Alagoas",
    "Bahia",
    "Ceara",
    "Maranhao",
    "Paraiba",
    "Pernambuco",
    "Piaui",
    "Rio Grande do Norte",
    "Sergipe",
    "Acre",
    "Amapa",
    "Amazonas",
    "Para",
    "Rondonia",
    "Roraima",
    "Tocantis",
    "Espirito Santo",
    "Minas Gerais",
    "Rio de Janeiro",
    "Sao Paulo",
    "Parana",
    "Rio Grande do Sul",
    "Santa Catarina",
];